auth:
  # Auth values should only be changed on first installation or when completely reinstalling rabbitmq
  username: rabbitmq
  password: DG8eMPFnsnRDnsO
  erlangCookie: w2otM5C5E76tOmwE5K2gmHrU0nSUtiin

commonLabels:
  app: rabbitmq
commonAnnotations: {}

podLabels:
  app: rabbitmq
  plusng.mercedesbenz.com/ingress: traefik-external

rabbitmqImage:
  registry: docker.io
  repository: bitnami/rabbitmq
  tag: 4.0.5-debian-12-r1

clusterOperator:
  watchAllNamespaces: false
  resources:
    requests:
      cpu: 100m
      memory: 300Mi
    limits:
      cpu: 1000m
      memory: 400Mi
  pdb:
    create: true
    maxUnavailable: "1"

  podLabels:
    app: rabbitmq
    plusng.mercedesbenz.com/ingress: traefik-external

  extraEnvVars:
    - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS # https://github.com/docker-library/rabbitmq/issues/249
      value: '-rabbitmq_management path_prefix "/rabbitmq"'

  # Network Policies
  networkPolicy:
    enabled: true
    allowExternal: false

  rbac:
    create: false
  serviceAccount:
    create: false
  # Prometheus configuration, plugin is added by default since 3.8
  metrics:
    enabled: false
    serviceMonitor:
      enabled: true

  customReadinessProbe:
    exec:
      command:
        - sh
        - -ec
        - rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms
    initialDelaySeconds: 10
    timeoutSeconds: 20
    periodSeconds: 30
  # Readiness:  exec [/bin/bash -ec rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms] delay=10s timeout=20s period=30s

  customLivenessProbe:
    exec:
      command:
        - sh
        - -ec
        - rabbitmq-diagnostics -q ping
    initialDelaySeconds: 120
    timeoutSeconds: 20
    periodSeconds: 30
  # Liveness:   exec [/bin/bash -ec rabbitmq-diagnostics -q ping] delay=120s timeout=20s period=30s