services:
  rabbitmq:
    container_name: "rabbitmq"
    image: "rabbitmq:4.0.2-management"
    hostname: "rabbitmq-0"
    env_file: rabbitmq.env
    networks:
      - rabbitmq
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  rabbitmq-producer:
    container_name: "rabbitmq-producer"
    image: "nzuwera/rabbitmq-producer:1.2.0"
    hostname: "rabbitmq-producer"
    env_file: rabbitmq-producer.env
    networks:
      - rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq-consumer:
    container_name: "rabbitmq-consumer"
    image: "nzuwera/rabbitmq-consumer:1.2.0"
    hostname: "rabbitmq-consumer"
    env_file: rabbitmq-consumer.env
    networks:
      - rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: "nginx"
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  rabbitmq:
    driver: bridge

volumes:
  rabbitmq-data: