replicaCount: 1

image:
  repository: nzuwera/rabbitmq-consumer
  tag: 1.0.1
  pullPolicy: Always

rabbitmq:
  clusterName: rabbitmq.rabbitmq-cluster.svc.cluster.local
  secretName: "rabbitmq-default-user"

service:
  type: ClusterIP
  port: 8080