replicaCount: 1

image:
  repository: nzuwera/rabbitmq-consumer
  tag: 1.0.2
  pullPolicy: IfNotPresent

rabbitmq:
  namespace: rabbitmq-cluster
  hostName: rabbitmq
  clusterDomain: cluster.local
  secretName: "rabbitmq-default-user"

service:
  type: ClusterIP
  port: 8080
  profile: k8s