apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rabbitmq-consumer.fullname" . }}
  labels:
    {{- include "rabbitmq-consumer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rabbitmq-consumer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rabbitmq-consumer.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: APP_PROFILE
              value: "{{ .Values.service.profile }}"
            - name: RABBITMQ_HOST
              value: "{{ .Values.rabbitmq.hostName }}.{{ .Values.rabbitmq.namespace}}.svc.{{ .Values.rabbitmq.clusterDomain}}"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.secretName }}
                  key: username
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.secretName }}
                  key: password